{
 "title": "Vector",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bytes Written / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "sum(irate(bytes_written[1m])) ", "legendFormat": "file_gen" },
    {
     "expr": "sum(rate(vector_processed_bytes_total[1m])) by (component_type)",
     "legendFormat": "{{component_type}}"
    }
   ]
  },
  {
   "title": "file_gen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Written / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(bytes_written[1m])) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  },
  { "title": "Vector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Processed Bytes / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vector_processed_bytes_total[1m])) by (component_type)"
    }
   ]
  },
  {
   "title": "Files Added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vector_files_added_total[1m])",
     "legendFormat": "{{file}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vector_open_files{component_name=\"file\"}",
     "legendFormat": "open files"
    }
   ]
  }
 ]
}