---
- include_role:
    name: golang

- name: Setup the tcp_test_server user
  user:
    name: tcp_test_server
    createhome: no
    home: /opt/tcp_test_server
    shell: /usr/sbin/nologin

- name: Create GOPATH src directory
  file:
    path: /home/{{ ansible_user }}/go/src/github.com/timberio
    state: directory

- name: Clone tcp_test_server
  git:
    repo: https://github.com/timberio/tcp_test_server
    dest: /home/{{ ansible_user }}/go/src/github.com/timberio/tcp_test_server

- name: Build and install tcp_test_server
  shell:
    cmd: /usr/local/go/bin/go build -o /usr/local/bin/tcp_test_server .
    chdir: /home/{{ ansible_user }}/go/src/github.com/timberio/tcp_test_server
  environment:
    GOPATH: "/home/{{ ansible_user }}/go"
    GO111MODULE: "off"
