[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

[transforms.lua]
  inputs = ["in"]
  type = "lua"
  source = """
event["new_field"] = "new value"
"""

[sinks.out]
  inputs   = ["lua"]
  type     = "socket"
  mode     = "tcp"
  address  = "{{ consumer_ip }}:{{ consumer_port }}"
  encoding = "text"
