data_dir = "/var/lib/vector"

[sources.in]
  type = "syslog"
  mode = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

##
## company-api
##

[transforms.company_api]
  type = "filter"
  inputs = ["in"]
  condition = '.appname == "company-api"'

[transforms.company_api_process]
  type = "remap"
  inputs = ["company_api"]
  source = '''
    parsed, err = parse_json(.message)
    if err == null && is_object(parsed) {
      . = merge!(., parsed)
    }
    .hostname = del(.host)
    .metadata_trace_id = string(.metadata.trace_id) ?? ""
    .metadata_guild_id = string(.metadata.guild_id) ?? ""
    .metadata_channel_id = string(.metadata.channel_id) ?? ""
    .metadata_method = string(.metadata.method) ?? ""
  '''

[sinks.company_api_http]
  type = "http"
  inputs = ["company_api_process"]
  uri = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec = "json"
  request.concurrency = 100
  request.rate_limit_duration_secs = 5
  request.rate_limit_num = 60

  [sinks.company_api_http.batch]
    max_bytes = 5245000
    timeout_secs = 5

  [sinks.company_api_http.buffer]
    type = "memory"
    max_events = 5000
    when_full = "block"

##
## company-admin
##

[transforms.company_admin]
  type = "filter"
  inputs = ["in"]
  condition = '.appname == "company-admin"'

[transforms.company_admin_process]
  type = "remap"
  inputs = ["company_admin"]
  source = '''
    parsed, err = parse_json(.message)
    if err == null && is_object(parsed) {
      . = merge!(., parsed)
    }
    .hostname = del(.host)
    .metadata_trace_id = string(.metadata.trace_id) ?? ""
    .metadata_method = string(.metadata.method) ?? ""
  '''

[sinks.company_admin_http]
  type = "http"
  inputs = ["company_admin_process"]
  uri = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec = "json"

##
## company-media-proxy
##

[transforms.company_media_proxy]
  type = "filter"
  inputs = ["in"]
  condition = '.appname == "company-media-proxy"'

[transforms.company_media_proxy_process]
  type = "remap"
  inputs = ["company_media_proxy"]
  source = '''
    parsed, err = parse_json(.message)
    if err == null && is_object(parsed) {
      . = merge!(., parsed)
    }
    .hostname = del(.host)
  '''

[sinks.company_media_proxy_http]
  type = "http"
  inputs = ["company_media_proxy_process"]
  uri = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec = "json"
  request.concurrency = 100
  request.rate_limit_duration_secs = 5
  request.rate_limit_num = 60

  [sinks.company_media_proxy_http.batch]
    max_bytes = 5245000
    timeout_secs = 5

  [sinks.company_media_proxy_http.buffer]
    type = "memory"
    max_events = 5000
    when_full = "block"

##
## company-unfurler
##

[transforms.company_unfurler]
  type = "filter"
  inputs = ["in"]
  condition = '.appname == "company-unfurler"'

[transforms.company_unfurler_process]
  type = "remap"
  inputs = ["company_unfurler"]
  source = '''
    .hostname = del(.host)
    parsed, err = parse_json(.message)
    if err == null && is_object(parsed) {
      . = merge!(., parsed)
    }
  '''

[transforms.company_unfurler_filter]
  type = "filter"
  inputs = ["company_unfurler_process"]
  condition = '.msg == "unfurl"'

[sinks.company_unfurler_http]
  type = "http"
  inputs = ["company_unfurler_filter"]
  uri = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec = "json"
  request.concurrency = 100
  request.rate_limit_duration_secs = 5
  request.rate_limit_num = 60

  [sinks.company_unfurler_http.batch]
    max_bytes = 5245000
    timeout_secs = 5

  [sinks.company_unfurler_http.buffer]
    type = "memory"
    max_events = 5000
    when_full = "block"

##
## audit
##

[transforms.audit_filter]
  type = "filter"
  inputs = ["in"]
  condition = '.appname == "audit"'

[transforms.audit_process]
  type = "remap"
  inputs = ["audit_filter"]
  source = '''
    .tag = del(.appname)
    .hostname = del(.host)
    .content = del(.message)
    .time = del(.timestamp)
  '''

[sinks.audit_http]
  type = "http"
  inputs = ["audit_process"]
  uri = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec = "json"
  request.concurrency = 100
  request.rate_limit_duration_secs = 5
  request.rate_limit_num = 60

  [sinks.audit_http.batch]
    max_bytes = 5245000
    timeout_secs = 5

  [sinks.audit_http.buffer]
    type = "memory"
    max_events = 5000
    when_full = "block"
