#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://docs.vector.dev/configuration
# ------------------------------------------------------------------------------
data_dir = "/var/lib/vector"

[sources.in]
type = "syslog"
mode = "tcp"
address = "0.0.0.0:{{ subject_port }}"

##
## company-api
##

[transforms.company_api]
type = "field_filter"
inputs = ["in"]
field = "appname"
value = "company-api"

[sinks.company_api_http]
type = "http"
inputs = ["company_api"]
uri = "http://{{ consumer_ip }}:{{ consumer_port }}"

[sinks.company_api_http.encoding]
codec = "ndjson"
except_fields = ["metadata.shard[0]", "metadata.shard[1]"]
only_fields = [
    "time",
    "endpoint",
    "hostname",
    "http_cf_ray",
    "http_debug_options",
    "http_content_length",
    "http_method",
    "http_referrer",
    "http_remote_addr",
    "http_response_time",
    "http_route",
    "http_status_code",
    "http_user_agent",
    "http_version",
    "ip_country",
    "ip_metro",
    "user_id",
    "metadata_trace_id",
    "metadata_guild_id",
    "metadata_channel_id",
    "metadata_method",
]
timestamp_format = "unix"

[sinks.company_api_http.request]
in_flight_limit = 1000
rate_limit_duration_secs = 5
rate_limit_num = 1000

[sinks.company_api_http.buffer]
type = "memory"
max_events = 5000
when_full = "block"

[sinks.company_api_http.batch]
max_size = 5245000
timeout_secs = 5

##
## company-admin
##

[transforms.company_admin]
type = "field_filter"
inputs = ["in"]
field = "appname"
value = "company-admin"

[sinks.company_admin_http]
type = "http"
inputs = ["company_admin"]
uri = "http://{{ consumer_ip }}:{{ consumer_port }}"

[sinks.company_admin_http.encoding]
codec = "ndjson"
only_fields = [
    "time",
    "endpoint",
    "hostname",
    "http_cf_ray",
    "http_debug_options",
    "http_content_length",
    "http_method",
    "http_referrer",
    "http_remote_addr",
    "http_response_time",
    "http_route",
    "http_status_code",
    "http_user_agent",
    "http_version",
    "user_id",
    "metadata_trace_id",
    "metadata_method",
]
timestamp_format = "unix"

[sinks.company_admin_http.request]
in_flight_limit = 1000
rate_limit_duration_secs = 5
rate_limit_num = 1000

[sinks.company_admin_http.buffer]
type = "memory"
max_events = 5000
when_full = "block"

[sinks.company_admin_http.batch]
max_size = 5245000
timeout_secs = 5

##
## company-media-proxy
##

[transforms.company_media_proxy]
type = "field_filter"
inputs = ["in"]
field = "appname"
value = "company-media-proxy"

[sinks.company_media_proxy_http]
type = "http"
inputs = ["company_media_proxy"]
uri = "http://{{ consumer_ip }}:{{ consumer_port }}"

[sinks.company_media_proxy_http.encoding]
codec = "ndjson"
only_fields = [
    "time",
    "hostname",
    "msg",
    "bhash",
    "bhash_duration",
    "input_type",
    "input_size_bytes",
    "input_height_px",
    "input_width_px",
    "output_type",
    "output_size_bytes",
    "output_height_px",
    "output_width_px",
    "downloaded_in_ms",
    "resized_in_ms",
    "request_type",
    "source",
    "source_host",
    "stacktrace",
]
timestamp_format = "unix"

[sinks.company_media_proxy_http.request]
in_flight_limit = 1000
rate_limit_duration_secs = 5
rate_limit_num = 1000

[sinks.company_media_proxy_http.buffer]
type = "memory"
max_events = 5000
when_full = "block"

[sinks.company_media_proxy_http.batch]
max_size = 5245000
timeout_secs = 5

##
## company-unfurler
##

[transforms.company_unfurler]
type = "field_filter"
inputs = ["in"]
field = "appname"
value = "company-unfurler"

[sinks.company_unfurler_http]
type = "http"
inputs = ["company_unfurler"]
uri = "http://{{ consumer_ip }}:{{ consumer_port }}"

[sinks.company_unfurler_http.encoding]
codec = "ndjson"
only_fields = ["time", "hostname", "host", "url", "msg", "success"]
timestamp_format = "unix"

[sinks.company_unfurler_http.request]
in_flight_limit = 1000
rate_limit_duration_secs = 5
rate_limit_num = 1000

[sinks.company_unfurler_http.buffer]
type = "memory"
max_events = 5000
when_full = "block"

##
## audit
##

[transforms.audit]
type = "field_filter"
inputs = ["in"]
field = "appname"
value = "audit"

[sinks.audit_http]
type = "http"
inputs = ["audit"]
uri = "http://{{ consumer_ip }}:{{ consumer_port }}"

[sinks.audit_http.encoding]
codec = "ndjson"
only_fields = ["time", "hostname", "content", "tag", "pid"]
timestamp_format = "unix"

[sinks.audit_http.request]
in_flight_limit = 1000
rate_limit_duration_secs = 5
rate_limit_num = 1000

[sinks.audit_http.buffer]
type = "memory"
max_events = 5000
when_full = "block"

##
## Debug
##
# [sinks.out]
# inputs = [
#   "audit_rename",
#   "company_api_rename",
#   "company_admin_rename",
#   "company_media_proxy_rename",
#   "company_unfurler_filter"
# ]
# type = "console"
# encoding = "json"
