[INPUT]
    Name             tail
    Path             {{ test_files_root }}*.log
    Tag              test_file
    Read_from_Head   True

[OUTPUT]
    Name   tcp
    Match  test_file
    Host   {{ consumer_ip }}
    Port   {{ consumer_port }}
    Format json_lines
