[sources.in]
  type               = "file"
  include            = ["{{ test_files_root }}*.log"]
  start_at_beginning = true

[sinks.out]
  inputs  = ["in"]
  type    = "socket"
  mode    = "tcp"
  address = "{{ consumer_ip }}:{{ consumer_port }}"
