#!/bin/bash
set -euo pipefail

TIMEOUT="$1"; shift
FILE="$1"; shift
SOCAT_ARGS=("$@")

exec timeout "$TIMEOUT" bash -euo pipefail <<CMD
while true; do
  socat $(printf "'%s' " "${SOCAT_ARGS[@]}") < "$FILE"
done
CMD
