---
- name: Create the /etc/fluent-bit directory
  file:
    path: /etc/fluent-bit
    state: directory

- name: Create the /var/lib/fluent-bit directory
  file:
    path: /var/lib/fluent-bit
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add fluent-bit apt-key
  apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Add fluent-bit apt repository
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/ubuntu/jammy jammy main'
    state: present
    filename: fluent-bit
    update_cache: yes

- name: Install fluent-bit
  apt:
    name: fluent-bit={{ version }}
    state: present

- name: Remove parsers.conf
  file:
    path: /etc/fluent-bit/parsers.conf
    state: absent

- name: Install fluent-bit daemon systemd script
  copy:
    src: fluent-bit.service
    dest: /etc/systemd/system/fluent-bit.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the fluent-bit service is stopped
  systemd:
    name: fluent-bit
    daemon_reload: yes
    enabled: no
    state: stopped
