[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "127.0.0.1:{{ subject_port }}"

[sinks.out]
  inputs  = ["in"]
  type    = "socket"
  mode    = "tcp"
  address = "{{ consumer_ip }}:{{ consumer_port }}"
