#!/bin/bash
set -euo pipefail

if [[ -n "${GENERATE_SSH_KEY:-""}" ]]; then
  export VECTOR_TEST_SSH_PRIVATE_KEY="$HOME/.ssh/id_rsa"
  export VECTOR_TEST_SSH_PUBLIC_KEY="$VECTOR_TEST_SSH_PRIVATE_KEY.pub"
  if [[ -f "$VECTOR_TEST_SSH_PRIVATE_KEY" ]]; then
    echo "Private key already exists at $VECTOR_TEST_SSH_PRIVATE_KEY, skipping key generation..." >&2
  else
    mkdir -p "$HOME/.ssh"
    chmod 0700 "$HOME/.ssh"
    ssh-keygen -b 4096 -t rsa -N "" -C "generated-in-docker" -f "$VECTOR_TEST_SSH_PRIVATE_KEY"
    export SSH_KEY_GENERATED=true
  fi
fi

if [[ -n "${INJECT_SSH_KEY:-""}" ]]; then
  export VECTOR_TEST_SSH_PRIVATE_KEY="${VECTOR_TEST_SSH_PRIVATE_KEY:-"$HOME/.ssh/id_rsa"}"
  export VECTOR_TEST_SSH_PUBLIC_KEY="$VECTOR_TEST_SSH_PRIVATE_KEY.pub"
  if [[ -f "$VECTOR_TEST_SSH_PRIVATE_KEY" ]]; then
    echo "Private key already exists at $VECTOR_TEST_SSH_PRIVATE_KEY, skipping key injection..." >&2
  else
    mkdir -p "$HOME/.ssh"
    chmod 0700 "$HOME/.ssh"
    echo -e "$INJECT_SSH_KEY" > "$VECTOR_TEST_SSH_PRIVATE_KEY"
    chmod 0600 "$VECTOR_TEST_SSH_PRIVATE_KEY"
    ssh-keygen -y -f "$VECTOR_TEST_SSH_PRIVATE_KEY" > "$VECTOR_TEST_SSH_PRIVATE_KEY.pub"
    export SSH_KEY_INJECTED=true
  fi
fi

exec "$@"
