---
- import_playbook: reset.yml

- hosts: '{{ test_namespace }}'
  become: true
  tasks:
    - set_fact:
        subject_ip: "{{ hostvars[groups['tag_Name_vector_test_' + user_id + '_' + test_name + '_' + test_configuration + '_subject'].0].private_ip_address }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_producer:&tag_TestIndex_0'
  become: true
  tasks:
    - set_fact:
        subject_port: "{{ subject_api_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_producer:&tag_TestIndex_1'
  become: true
  tasks:
    - set_fact:
        subject_port: "{{ subject_admin_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_producer:&tag_TestIndex_2'
  become: true
  tasks:
    - set_fact:
        subject_port: "{{ subject_media_proxy_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_producer:&tag_TestIndex_3'
  become: true
  tasks:
    - set_fact:
        subject_port: "{{ subject_unfurler_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_producer:&tag_TestIndex_4'
  become: true
  tasks:
    - set_fact:
        subject_port: "{{ subject_audit_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_consumer'
  become: true
  tasks:
    - include_role:
        name: http_test_server
      vars:
        action: start_and_wait
        port: "{{ consumer_port }}"

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

# - hosts: '{{ test_namespace }}:&tag_TestRole_producer'
#   become: true
#   tasks:
#     - name: Wait for port {{ subject_ip }}:{{ subject_port }} to become available
#       wait_for:
#         host: "{{ subject_ip }}"
#         port: "{{ subject_port }}"
#         delay: 1

#     - name: Warmup {{ test_subject }}
#       include_role:
#         name: socat
#       vars:
#         action: send
#         address: "tcp:{{ subject_ip }}:{{ subject_port }}"
#         file: "{{ test_file }}"
#         timeout: 10

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: Start profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: start

- hosts: '{{ test_namespace }}:&tag_TestRole_producer'
  become: true
  tasks:
    - name: Pipe test data to {{ test_subject }}
      include_role:
        name: socat
      vars:
        action: send
        address: "tcp:{{ subject_ip }}:{{ subject_port }}"
        file: "{{ test_file }}"
        timeout: 60

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: Stop profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: stop

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop

- hosts: '{{ test_namespace }}:&tag_TestRole_consumer'
  become: true
  tasks:
    - name: Stop http_test_server
      include_role:
        name: http_test_server
      vars:
        action: stop
