input {
  tcp {
    host => "0.0.0.0"
    port => {{ subject_port }}
    codec => line
  }
}

filter {
  grok {
    match => { "message" => "^(?<host>[\w\.]+) - (?<user>[\w]+) (?<bytes_in>[\d]+) \[(?<timestamp>[^\]]*)\] \"(?<method>[\w]+) (?<path>[^\"]*)\" (?<status>[\d]+) (?<bytes_out>[\d]+)$" }
  }
}

output {
  tcp {
    host => "{{ consumer_ip }}"
    port => {{ consumer_port }}
    codec => line
  }
}
