[SERVICE]
    Parsers_File /etc/fluent-bit/td-agent-bit.parsers.conf

[INPUT]
    Name      tcp
    Listen    0.0.0.0
    Port      {{ subject_port }}
    Format    none
    Separator \n

[FILTER]
    Name     parser
    Match    *
    Key_Name log
    Parser   apache

[OUTPUT]
    Name   tcp
    Match  *
    Host   {{ consumer_ip }}
    Port   {{ consumer_port }}
    Format json_lines
