[PARSER]
    Name   apache
    Format regex
    Regex  ^(?<host>[\w\.]+) - (?<user>[\w]+) (?<bytes_in>[\d]+) \[(?<timestamp>[^\]]*)\] "(?<method>[\w]+) (?<path>[^"]*)" (?<status>[\d]+) (?<bytes_out>[\d]+)$
