[INPUT]
    Name      tcp
    Listen    0.0.0.0
    Port      {{ subject_port }}
    Tag       tcp_in
    Format    none
    Separator \n

[OUTPUT]
    Name   tcp
    Match  tcp_in
    Host   {{ consumer_ip }}
    Port   {{ consumer_port }}
    Format json_lines
