[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

[sinks.out]
  inputs   = ["in"]
  type     = "socket"
  mode     = "tcp"
  address  = "{{ consumer_ip }}:{{ consumer_port }}"
  encoding = "text"
