#!/usr/bin/env ruby

# This script print a table of comparisons.
#
# We use Ruby since we have to mangle with a complex data structure.
# Trying to print this table using bash utilities such as jq was
# painful.

require 'json'

require_relative "athena"
require_relative "table_print"

results_json = ARGV[0]

if results_json.nil?
  raise "You must pass the query results JSON as the first argument"
end

def pivot(hashes)
  pivoted_hashes = []

  hashes.group_by { |h| "#{h.fetch('name')} (#{h.fetch('configuration')})" }.each do |name, hashes|
    pivoted_hash = {"name" => name}

    hashes.each do |hash|
      subject = hash["subject"]
      pivoted_hash[subject] = "#{hash.fetch("count")}/#{hash.fetch("avg_duration").round(1)}s/#{hash.fetch("avg_cpu_usr").round(1)}cpu/#{hash.fetch("avg_duration").round(2)}mem"
    end

    pivoted_hashes << pivoted_hash
  end

  pivoted_hashes
end


results = JSON.parse(results_json)
result_set = results.fetch("ResultSet")
rows = result_set,.fetch("Rows")
result_set_metadata = result_set.fetch("ResultSetMetadata")
hashes = transform_to_hashes!(rows, result_set_metadata)
hashes = pivot(hashes)

puts ""
puts "Comparison - quantity/avg time/avg cpu/avg mem"
puts "--------------------------------------------------------"

tp hashes
