[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

[sinks.out]
  inputs                       = ["in"]
  type                         = "http"
  uri                          = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec               = "json"
  batch.max_bytes              = 102400
  batch.timeout_secs           = 5
  request.concurrency          = "adaptive"

